export CONDA_PATH="/opt/miniconda3"
export ENV="airflow"
export PORT="8686"
export AIRFLOW__CORE__INTERNAL_API_URL="http://127.0.0.1:8686"
export AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS="admin:admin"