name: airflow
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - numpy
  - pandas
  - db-dtypes
  - pandas-gbq
  - bunch
  - google-cloud-storage
  - libgcc
  - pip:
    - apache-airflow
    - apache-airflow-providers-ftp
    - apache-airflow-providers-http
    - apache-airflow-providers-imap
    - apache-airflow-providers-mysql
    - apache-airflow-providers-slack
    - mysql-connector-python
    - mysqlclient
    - apache-airflow-providers-cncf-kubernetes
